# WARNING: this file is not suitable for production, please use with caution
version: '3'

services:
  web:
    image: image_colorization_api
    build: .
    command: gunicorn -b 0.0.0.0:5000 image_colorization_api.wsgi:app
    env_file:
      - ./.flaskenv
    environment:
      - DATABASE_URI=sqlite:////db/image_colorization_api.db
    volumes:
      - ./image_colorization_api:/code/image_colorization_api
      - ./db/:/db/
    ports:
      - "5000:5000"
